import express,{Request,Response,NextFunction} from 'express';
import cors from 'cors'; import path from 'node:path'; import fs from 'node:fs'; import {fileURLToPath} from 'node:url';
import {AgentConfig} from './src/types.js'; import * as riskEngine from './src/risk_engine.js'; import * as policyEngine from './src/policy_engine.js'; import * as audit from './src/audit.js'; import { analyzeWithAI, runAgent, securityEvaluate, AI_MODELS } from './src/ai_gateway.js'; import { initDb,dbEnabled,loadAgents,saveAgent,saveDecision,castIdeaVote,getIdeaVoteStats } from './src/db.js'; import { initAuthDb,createAccount,login,getSession,logout } from './src/auth.js'; import { liveOverview,livePolicies,liveIncidents,liveAudit } from './src/control_plane_db.js';
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),AGENTS_PATH=path.join(__dirname,'config','agents.json'),STATIC_DIR=path.join(__dirname,'static'); const app=express(); app.use(cors({origin:true,credentials:true})); app.use(express.json({limit:'1mb'})); let agentRegistry:Record<string,AgentConfig>={}; try{agentRegistry=JSON.parse(fs.readFileSync(AGENTS_PATH,'utf8'))}catch{agentRegistry={}}
const cookie=(req:Request,n:string)=>req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith(n+'='))?.slice(n.length+1);
async function requireAuth(req:Request,res:Response,next:NextFunction){const user=await getSession(cookie(req,'arexid_session'));if(!user)return res.status(401).json({error:'authentication_required'});(req as any).user=user;(req as any).organizationId=user.organization_id;next()}
app.use('/static',express.static(STATIC_DIR)); app.get('/',(_q,r)=>r.sendFile(path.join(STATIC_DIR,'auth.html'))); app.get('/login',(_q,r)=>r.sendFile(path.join(STATIC_DIR,'auth.html'))); app.get('/dashboard',(_q,r)=>r.sendFile(path.join(STATIC_DIR,'dashboard.html'))); app.get('/index.html',(_q,r)=>r.sendFile(path.join(STATIC_DIR,'auth.html'))); for(const p of ['landing','docs','pricing','security','api'])app.get('/'+p,(_q,r)=>r.sendFile(path.join(STATIC_DIR,p+'.html')));
app.post('/v1/auth/signup',async(req,res)=>{try{const b=req.body||{};if(!b.email||!b.password||!b.name||!b.company)return res.status(400).json({error:'name,email,password,and company_are_required'});const token=await createAccount(String(b.email),String(b.password),String(b.name),String(b.company));res.cookie('arexid_session',token,{httpOnly:true,secure:true,sameSite:'lax',maxAge:2592000000});res.json({ok:true})}catch(e){res.status(400).json({error:e instanceof Error?e.message:'signup_failed'})}});
app.post('/v1/auth/login',async(req,res)=>{try{const b=req.body||{};const token=await login(String(b.email||''),String(b.password||''));res.cookie('arexid_session',token,{httpOnly:true,secure:true,sameSite:'lax',maxAge:2592000000});res.json({ok:true})}catch(e){res.status(401).json({error:e instanceof Error?e.message:'invalid_credentials'})}}); app.get('/v1/auth/me',async(req,res)=>{const user=await getSession(cookie(req,'arexid_session'));if(!user)return res.status(401).json({error:'not_authenticated'});res.json({user})}); app.post('/v1/auth/logout',async(req,res)=>{await logout(cookie(req,'arexid_session'));res.clearCookie('arexid_session');res.json({ok:true})});
app.get('/health',(_q,r)=>r.json({status:'ok',database:dbEnabled,agent_model:AI_MODELS.agent,security_model:AI_MODELS.security}));
app.get('/v1/idea-vote',async(_q,res)=>{try{res.json(await getIdeaVoteStats())}catch(e){res.status(503).json({error:e instanceof Error?e.message:'vote_stats_failed'})}}); app.post('/v1/idea-vote',async(req,res)=>{try{const b=req.body||{};if(b.vote!=='yes'&&b.vote!=='no')return res.status(400).json({error:'vote_must_be_yes_or_no'});const willing=Boolean(b.willing_to_pay);const price=willing&&b.price_eur!==''&&b.price_eur!=null?Number(b.price_eur):null;if(price!=null&&(!Number.isFinite(price)||price<0))return res.status(400).json({error:'invalid_price'});res.json(await castIdeaVote({vote:b.vote,willing_to_pay:willing,price_eur:price,company_size:String(b.company_size||''),role:String(b.role||'')}))}catch(e){res.status(503).json({error:e instanceof Error?e.message:'vote_failed'})}});
app.use('/v1',requireAuth);
app.get('/v1/overview',async(req,res)=>{try{res.json({...await liveOverview((req as any).organizationId),organization_id:(req as any).organizationId,agent_model:AI_MODELS.agent,security_model:AI_MODELS.security})}catch(e){res.status(503).json({error:e instanceof Error?e.message:'overview_unavailable'})}});
app.get('/v1/agents',async(req,res)=>{const o=(req as any).organizationId;if(dbEnabled)agentRegistry={...agentRegistry,...await loadAgents(o)};res.json(Object.entries(agentRegistry).filter(([,v])=>(v.organization_id||o)===o).map(([agent_id,v])=>({agent_id,...v,model:AI_MODELS.agent,fallback_model:AI_MODELS.agent})))});
app.post('/v1/agents',async(req,res)=>{const b=req.body||{},o=(req as any).organizationId,id=String(b.agent_id||b.id||b.name||'').trim().toLowerCase().replace(/[^a-z0-9_-]/g,'-');if(!id||!b.name)return res.status(400).json({error:'agent_id and name are required'});if(agentRegistry[id]&&agentRegistry[id].organization_id===o)return res.status(409).json({error:'agent_exists'});const now=new Date().toISOString();const a:AgentConfig={name:String(b.name),tier:String(b.tier||'standard'),status:b.status==='disabled'?'disabled':'active',owner:String(b.owner||''),purpose:String(b.purpose||''),model:AI_MODELS.agent,fallback_model:AI_MODELS.agent,tools:Array.isArray(b.tools)?b.tools:[],permissions:Array.isArray(b.permissions)?b.permissions:[],max_autonomous_amount:Number(b.max_autonomous_amount??500),required_human_approval_above:Number.POSITIVE_INFINITY,blocked_action_types:Array.isArray(b.blocked_action_types)?b.blocked_action_types:[],hard_constraints:b.hard_constraints&&typeof b.hard_constraints==='object'?b.hard_constraints:{},human_operator:'System',organization_id:o,created_at:now,updated_at:now};agentRegistry[id]=a;await saveAgent(id,a);res.status(201).json({agent_id:id,...a})});
app.patch('/v1/agents/:agent_id',async(req,res)=>{const id=req.params.agent_id,o=(req as any).organizationId;if(!agentRegistry[id]||agentRegistry[id].organization_id!==o)return res.status(404).json({error:'agent_not_found'});agentRegistry[id]={...agentRegistry[id],...req.body,organization_id:o,model:AI_MODELS.agent,fallback_model:AI_MODELS.agent,updated_at:new Date().toISOString()};await saveAgent(id,agentRegistry[id]);res.json({agent_id:id,...agentRegistry[id]})});
app.post('/v1/actions/evaluate',async(req,res)=>{const {agent_id,action_type,amount=null,parameters=null,description=''}=req.body||{},o=(req as any).organizationId;if(dbEnabled)agentRegistry={...agentRegistry,...await loadAgents(o)};const agent=agentRegistry[agent_id];if(!agent||agent.organization_id!==o)return res.status(404).json({error:'agent_not_found'});try{const risk=riskEngine.computeRisk(action_type,amount,(agent as any).risk_weights);const [deterministicDecision,reason,policy_triggered]=policyEngine.evaluate(agent,action_type,amount,risk,parameters,audit.policies,agent_id);const security=await securityEvaluate({agent_id,action_type,description,amount,parameters,risk_score:risk.risk_score,deterministic_decision:deterministicDecision});const decision=deterministicDecision==='blocked'||security.verdict==='BLOCK'?'blocked':'approved';const result={decision,reason:security.verdict==='BLOCK'?`Security layer: ${security.text}`:reason,policy_triggered,risk_score:risk.risk_score,risk_breakdown:risk.breakdown,factors:risk.factors,security:{model:security.model,verdict:security.verdict,analysis:security.text},agent_model:AI_MODELS.agent};await saveDecision(o,agent_id,action_type,decision,risk.risk_score,result);res.json(result)}catch(e){res.status(400).json({error:e instanceof Error?e.message:'evaluation_failed'})}});
app.post('/v1/agents/:agent_id/run',async(req,res)=>{const o=(req as any).organizationId;if(dbEnabled)agentRegistry={...agentRegistry,...await loadAgents(o)};const agent=agentRegistry[req.params.agent_id];if(!agent||agent.organization_id!==o)return res.status(404).json({error:'agent_not_found'});try{const prompt=String(req.body?.prompt||req.body?.task||'');if(!prompt)return res.status(400).json({error:'prompt_required'});const security=await securityEvaluate({agent_id:req.params.agent_id,action_type:'agent_run',description:prompt,risk_score:0,deterministic_decision:'eligible'});if(security.verdict==='BLOCK')return res.status(403).json({decision:'blocked',security});const result=await runAgent(prompt);res.json({decision:'allowed',model:result.model,text:result.text,security})}catch(e){res.status(502).json({error:e instanceof Error?e.message:'agent_execution_failed'})}});
app.post('/v1/ai/analyze',async(req,res)=>{try{const {prompt,model}=req.body||{};if(!prompt)return res.status(400).json({error:'prompt_required'});const selected=Object.values(AI_MODELS).includes(model)?model:AI_MODELS.agent;res.json(await analyzeWithAI(String(prompt),selected))}catch(e){res.status(502).json({error:e instanceof Error?e.message:'ai_gateway_error'})}}); app.get('/v1/ai/models',(_q,res)=>res.json({agent:AI_MODELS.agent,security:AI_MODELS.security,models:Object.entries(AI_MODELS).map(([name,id])=>({name,id,free:id.endsWith('-free')}))}));
app.get('/v1/policies',async(req,res)=>res.json(await livePolicies((req as any).organizationId))); app.get('/v1/audit',async(req,res)=>res.json(await liveAudit((req as any).organizationId,Number(req.query.limit)||30))); app.get('/v1/escalations',(_q,res)=>res.json([])); app.get('/v1/incidents',async(req,res)=>res.json(await liveIncidents((req as any).organizationId)));
Promise.all([initDb(),initAuthDb()]).catch(err=>console.error('Database initialization failed',err)); export default app; if(process.env.VERCEL!=='1')app.listen(3000,'0.0.0.0',()=>console.log('Arexid listening on http://0.0.0.0:3000'));