import { createClient } from '@libsql/client';
import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
const url=process.env.TURSO_DATABASE_URL,authToken=process.env.TURSO_AUTH_TOKEN;
const db=url&&authToken?createClient({url,authToken}):null;
const hashPassword=(p:string,s:string)=>scryptSync(p,s,64).toString('hex');
export type AuthUser={id:string,email:string,name:string,organization_id:string,organization_name:string};
export async function initAuthDb(){if(!db)return;await db.batch([`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,organization_id TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,`CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,`CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at)`],'write')}
export async function createAccount(email:string,password:string,name:string,company:string){if(!db)throw new Error('database_unavailable');const clean=email.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(clean))throw new Error('invalid_email');if(password.length<8)throw new Error('password_too_short');const exists=await db.execute({sql:'SELECT id FROM users WHERE email=?',args:[clean]});if(exists.rows.length)throw new Error('email_already_registered');const orgId='org_'+randomBytes(12).toString('hex'),userId='usr_'+randomBytes(12).toString('hex'),salt=randomBytes(16).toString('hex'),now=new Date().toISOString();const slug=company.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||`company-${userId.slice(-6)}`;await db.batch([{sql:'INSERT INTO organizations(id,name,slug,created_at,updated_at) VALUES(?,?,?,?,?)',args:[orgId,company.trim()||`${name.trim()}'s organization`,slug,now,now]},{sql:'INSERT INTO users(id,email,name,password_hash,password_salt,organization_id,created_at) VALUES(?,?,?,?,?,?,?)',args:[userId,clean,name.trim()||'User',hashPassword(password,salt),salt,orgId,now]}],'write');return createSession(userId)}
export async function login(email:string,password:string){if(!db)throw new Error('database_unavailable');const r=await db.execute({sql:'SELECT id,password_hash,password_salt FROM users WHERE email=?',args:[email.trim().toLowerCase()]});const u=r.rows[0];if(!u)throw new Error('invalid_credentials');const expected=Buffer.from(String(u.password_hash),'hex'),actual=Buffer.from(hashPassword(password,String(u.password_salt)),'hex');if(expected.length!==actual.length||!timingSafeEqual(expected,actual))throw new Error('invalid_credentials');return createSession(String(u.id))}
async function createSession(userId:string){if(!db)throw new Error('database_unavailable');const token=randomBytes(32).toString('hex'),expires=new Date(Date.now()+1000*60*60*24*30).toISOString();await db.execute({sql:'INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)',args:[token,userId,expires]});return token}
export async function getSession(token:string|undefined):Promise<AuthUser|null>{if(!db||!token)return null;const r=await db.execute({sql:`SELECT u.id,u.email,u.name,u.organization_id,o.name organization_name,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id JOIN organizations o ON o.id=u.organization_id WHERE s.token=? AND s.expires_at>?`,args:[token,new Date().toISOString()]});const x=r.rows[0];return x?{id:String(x.id),email:String(x.email),name:String(x.name),organization_id:String(x.organization_id),organization_name:String(x.organization_name)}:null}
export async function logout(token:string|undefined){if(db&&token)await db.execute({sql:'DELETE FROM sessions WHERE token=?',args:[token]})}
