import express,{type Request,type Response,type NextFunction} from 'express';
import {createClient} from '@libsql/client';
import {getSession} from './auth.js';
import {PLANS,normalizePlan,createCheckoutSession,createPortalSession,verifyWebhook} from './stripe.js';

const router=express.Router();
const db=process.env.TURSO_DATABASE_URL&&process.env.TURSO_AUTH_TOKEN?createClient({url:process.env.TURSO_DATABASE_URL,authToken:process.env.TURSO_AUTH_TOKEN}):null;
const cookie=(req:Request,n:string)=>req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith(n+'='))?.slice(n.length+1);
const origin=(req:Request)=>`${req.protocol}://${req.get('host')}`;
async function ensure(){if(!db)return;await db.execute(`CREATE TABLE IF NOT EXISTS stripe_events (event_id TEXT PRIMARY KEY,created_at TEXT NOT NULL)`).catch(()=>{})}
async function auth(req:Request,res:Response,next:NextFunction){const user=await getSession(cookie(req,'conforva_session'));if(!user)return res.status(401).json({error:'authentication_required'});(req as any).user=user;(req as any).organizationId=user.organization_id;next()}
async function account(o:string){if(!db)return null;await ensure();const r=await db.execute({sql:'SELECT stripe_customer_id,stripe_subscription_id,plan,status,period_end,cancel_at_period_end FROM billing_accounts WHERE organization_id=?',args:[o]});const x=r.rows[0];const plan=normalizePlan(String(x?.plan||''));return x?{customer_id:String(x.stripe_customer_id||''),subscription_id:String(x.stripe_subscription_id||''),plan,status:x.status?String(x.status):null,period_end:x.period_end?String(x.period_end):null,cancel_at_period_end:Boolean(Number(x.cancel_at_period_end||0)),included_usage_eur:Number((PLANS as any)[plan||'']?.included_usage_eur||0),max_agents:Number((PLANS as any)[plan||'']?.max_agents||0)}:null}
async function setAccount(o:string,data:Record<string,unknown>){if(!db)throw new Error('database_unavailable');await ensure();const old=await account(o);await db.execute({sql:`INSERT INTO billing_accounts(organization_id,stripe_customer_id,stripe_subscription_id,plan,status,period_end,cancel_at_period_end,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(organization_id) DO UPDATE SET stripe_customer_id=excluded.stripe_customer_id,stripe_subscription_id=excluded.stripe_subscription_id,plan=excluded.plan,status=excluded.status,period_end=excluded.period_end,cancel_at_period_end=excluded.cancel_at_period_end,updated_at=excluded.updated_at`,args:[o,data.customer_id ?? (old?.customer_id || null),data.subscription_id ?? (old?.subscription_id || null),data.plan ? (normalizePlan(String(data.plan)) || null) : (old?.plan || null),data.status ?? (old?.status || null),data.period_end ?? (old?.period_end || null),data.cancel_at_period_end == null ? (old?.cancel_at_period_end ? 1 : 0) : (Boolean(data.cancel_at_period_end) ? 1 : 0),new Date().toISOString()]});return account(o)}
router.use(express.json({limit:'64kb',verify:(req,_res,buf)=>{(req as any).rawBody=Buffer.from(buf)}}));
router.get('/',auth,async(req,res)=>{try{res.json({plans:PLANS,billing:await account((req as any).organizationId)})}catch(e){res.status(503).json({error:e instanceof Error?e.message:'billing_unavailable'})}});
router.post('/checkout',auth,async(req,res)=>{try{const plan=normalizePlan(String(req.body?.plan??req.body?.selectedPlan??''));if(!plan)return res.status(400).json({error:'invalid_plan'});const user=(req as any).user;const existing=await account(user.organization_id);if(existing?.status==='active'||existing?.status==='trialing')return res.status(409).json({error:'active_subscription_exists',portal:true});const session=await createCheckoutSession({customerId:existing?.customer_id||undefined,email:user.email,name:user.name,organizationId:user.organization_id,plan,successUrl:`${origin(req)}/dashboard#billing?success=1`,cancelUrl:`${origin(req)}/pricing?canceled=1`,trialDays:14});res.json({url:session.url,id:session.id,trial_days:14,plan})}catch(e){res.status(503).json({error:e instanceof Error?e.message:'checkout_failed'})}});
router.post('/portal',auth,async(req,res)=>{try{const a=await account((req as any).organizationId);if(!a?.customer_id)return res.status(400).json({error:'no_stripe_customer'});const session=await createPortalSession(a.customer_id,`${origin(req)}/dashboard#billing`);res.json({url:session.url})}catch(e){res.status(503).json({error:e instanceof Error?e.message:'portal_failed'})}});
router.post('/webhook',async(req,res)=>{try{const event=verifyWebhook((req as any).rawBody,String(req.headers['stripe-signature']||''));await ensure();if(db){const seen=await db.execute({sql:'SELECT event_id FROM stripe_events WHERE event_id=?',args:[String(event.id||'')]});if(seen.rows.length)return res.json({received:true,duplicate:true});await db.execute({sql:'INSERT INTO stripe_events(event_id,created_at) VALUES(?,?)',args:[String(event.id||''),new Date().toISOString()]})}const obj=event.data?.object||{};const metadata=obj.metadata||obj.subscription_details?.metadata||{};const org=String(metadata.organization_id||'');if(org){if(event.type==='checkout.session.completed'){const plan=normalizePlan(String(metadata.plan||''));await setAccount(org,{customer_id:String(obj.customer||''),subscription_id:String(obj.subscription||''),plan,status:'trialing'})}else if(event.type==='customer.subscription.created'||event.type==='customer.subscription.updated'){const plan=normalizePlan(String(metadata.plan||''));await setAccount(org,{customer_id:String(obj.customer||''),subscription_id:String(obj.id||''),plan:plan||undefined,status:String(obj.status||''),period_end:obj.current_period_end?new Date(Number(obj.current_period_end)*1000).toISOString():null,cancel_at_period_end:Boolean(obj.cancel_at_period_end)})}else if(event.type==='customer.subscription.deleted'){await setAccount(org,{status:'canceled',subscription_id:String(obj.id||''),customer_id:String(obj.customer||'')})}else if(event.type==='invoice.paid'&&obj.subscription){const plan=normalizePlan(String(metadata.plan||''));if(plan)await setAccount(org,{plan,status:'active'})}}res.json({received:true})}catch(e){res.status(400).json({error:e instanceof Error?e.message:'invalid_webhook'})}});
export default router;