import { createClient, type Client } from '@libsql/client';
import type { AgentConfig, PolicyRule } from './types.js';
import { randomBytes, createHash } from 'node:crypto';
import { PLANS } from './stripe.js';
const url=process.env.TURSO_DATABASE_URL,authToken=process.env.TURSO_AUTH_TOKEN;
export const dbEnabled=Boolean(url&&authToken); const client:Client|null=dbEnabled?createClient({url:url!,authToken:authToken!}):null;
export async function initDb(){if(!client)return;await client.batch([`CREATE TABLE IF NOT EXISTS organizations (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,`CREATE TABLE IF NOT EXISTS agents (agent_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',fallback_model TEXT,purpose TEXT,max_autonomous_amount REAL DEFAULT 500,required_human_approval_above REAL,hard_constraints TEXT NOT NULL DEFAULT '{}',blocked_action_types TEXT NOT NULL DEFAULT '[]',capabilities TEXT NOT NULL DEFAULT '[]',permissions TEXT NOT NULL DEFAULT '[]',risk_profile TEXT NOT NULL DEFAULT '{}',integrations TEXT NOT NULL DEFAULT '[]',passport TEXT)`,`CREATE TABLE IF NOT EXISTS decisions (id INTEGER PRIMARY KEY AUTOINCREMENT,organization_id TEXT NOT NULL,agent_id TEXT NOT NULL,action_type TEXT NOT NULL,decision TEXT NOT NULL,risk_score REAL,data TEXT NOT NULL,created_at TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS idea_votes (id INTEGER PRIMARY KEY AUTOINCREMENT,idea_key TEXT NOT NULL DEFAULT 'conforva',vote TEXT NOT NULL CHECK(vote IN ('yes','no')),willing_to_pay INTEGER NOT NULL DEFAULT 0,price_eur REAL,company_size TEXT,role TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,`CREATE TABLE IF NOT EXISTS api_keys (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,name TEXT NOT NULL,key_prefix TEXT NOT NULL,secret_hash TEXT NOT NULL,environment TEXT NOT NULL DEFAULT 'production',created_at TEXT NOT NULL,revoked_at TEXT)`,`CREATE TABLE IF NOT EXISTS usage_events (id INTEGER PRIMARY KEY AUTOINCREMENT,organization_id TEXT NOT NULL,api_key_id TEXT,model TEXT,request_type TEXT NOT NULL,units INTEGER NOT NULL DEFAULT 1,input_tokens INTEGER NOT NULL DEFAULT 0,output_tokens INTEGER NOT NULL DEFAULT 0,cost_eur REAL NOT NULL DEFAULT 0,created_at TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS billing_accounts (organization_id TEXT PRIMARY KEY,stripe_customer_id TEXT UNIQUE,stripe_subscription_id TEXT UNIQUE,plan TEXT,status TEXT,period_end TEXT,cancel_at_period_end INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL)`,`CREATE INDEX IF NOT EXISTS idx_agents_org ON agents(organization_id)`,`CREATE INDEX IF NOT EXISTS idx_decisions_org ON decisions(organization_id)`,`CREATE INDEX IF NOT EXISTS idx_idea_votes ON idea_votes(idea_key)`,`CREATE INDEX IF NOT EXISTS idx_api_keys_org ON api_keys(organization_id)`,`CREATE INDEX IF NOT EXISTS idx_usage_org ON usage_events(organization_id)`],'write')}
export async function loadAgents(organizationId:string):Promise<Record<string,AgentConfig>>{if(!client)return{};const r=await client.execute({sql:'SELECT agent_id,data FROM agents WHERE organization_id=?',args:[organizationId]});return Object.fromEntries(r.rows.map(x=>[String(x.agent_id),JSON.parse(String(x.data)) as AgentConfig]))}
export async function listPolicyRules(organizationId:string):Promise<PolicyRule[]>{if(!client)return[];const r=await client.execute({sql:'SELECT id,name,description,status,priority,target_agents,conditions,version,updated_at,created_at FROM policies WHERE organization_id=? ORDER BY priority ASC,updated_at DESC',args:[organizationId]});return r.rows.map(x=>({id:String(x.id),name:String(x.name||''),category:'',organization_id:organizationId,targetAgents:parseArray(x.target_agents),conditions:parseConditions(x.conditions),status:normalizePolicyStatus(x.status),description:String(x.description||''),lastUpdated:String(x.updated_at||x.created_at||'')}))}
function parseArray(value:unknown):string[]{if(Array.isArray(value))return value.map(String);try{const parsed=JSON.parse(String(value??'[]'));return Array.isArray(parsed)?parsed.map(String):[]}catch{return[]}}
function parseConditions(value:unknown):PolicyRule['conditions']{try{const parsed=JSON.parse(String(value??'[]'));if(!Array.isArray(parsed))return[];return parsed.filter((c:any)=>c&&typeof c==='object'&&typeof c.field==='string'&&typeof c.operator==='string'&&['<=','>=','>','<','==','!=','in','contains'].includes(c.operator)&&['ALLOW','HUMAN_REVIEW','BLOCK'].includes(String(c.action).toUpperCase())).map((c:any)=>({...c,action:String(c.action).toUpperCase()})) as PolicyRule['conditions']}catch{return[]}}
function normalizePolicyStatus(value:unknown):PolicyRule['status']{const s=String(value||'draft').toLowerCase();return s==='active'||s==='paused'||s==='draft'?s:'draft'}
export async function saveAgent(id:string,a:AgentConfig){if(!client)throw new Error('database_unavailable');const now=new Date().toISOString();const existing=await client.execute({sql:'SELECT agent_id FROM agents WHERE agent_id=? AND organization_id=?',args:[id,a.organization_id||'']});if(existing.rows.length===0){const billing=await client.execute({sql:'SELECT plan,status FROM billing_accounts WHERE organization_id=?',args:[a.organization_id||'']});const plan=String(billing.rows[0]?.plan||'');const status=String(billing.rows[0]?.status||'');const maxAgents=Number((PLANS as any)[plan]?.max_agents||0);if(!maxAgents||!['active','trialing'].includes(status))throw new Error('active_plan_required');const count=await client.execute({sql:'SELECT COUNT(*) count FROM agents WHERE organization_id=?',args:[a.organization_id||'']});if(Number(count.rows[0]?.count||0)>=maxAgents)throw new Error('agent_limit_reached')}
await client.execute({sql:`INSERT INTO agents(agent_id,organization_id,data,created_at,updated_at,status,fallback_model,purpose,max_autonomous_amount,required_human_approval_above,hard_constraints,blocked_action_types,capabilities,permissions,risk_profile,integrations,passport) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(agent_id) DO UPDATE SET organization_id=excluded.organization_id,data=excluded.data,updated_at=excluded.updated_at,status=excluded.status,fallback_model=excluded.fallback_model,purpose=excluded.purpose,max_autonomous_amount=excluded.max_autonomous_amount,required_human_approval_above=excluded.required_human_approval_above,hard_constraints=excluded.hard_constraints,blocked_action_types=excluded.blocked_action_types,capabilities=excluded.capabilities,permissions=excluded.permissions,risk_profile=excluded.risk_profile,integrations=excluded.integrations,passport=excluded.passport`,args:[id,a.organization_id||'',JSON.stringify(a),a.created_at||now,a.updated_at||now,a.status||'active',a.fallback_model||null,a.purpose||null,a.max_autonomous_amount??500,a.required_human_approval_above??null,JSON.stringify(a.hard_constraints||{}),JSON.stringify((a as any).blocked_action_types||[]),JSON.stringify((a as any).capabilities||[]),JSON.stringify(a.permissions||[]),JSON.stringify((a as any).risk_profile||{}),JSON.stringify((a as any).integrations||[]),(a as any).passport?JSON.stringify((a as any).passport):null]})}
export async function saveDecision(o:string,id:string,type:string,decision:string,risk:number,data:unknown){if(!client)throw new Error('database_unavailable');await client.execute({sql:'INSERT INTO decisions(organization_id,agent_id,action_type,decision,risk_score,data,created_at) VALUES(?,?,?,?,?,?,?)',args:[o,id,type,decision,risk,JSON.stringify(data),new Date().toISOString()]})}
export async function castIdeaVote(input:{vote:'yes'|'no';willing_to_pay:boolean;price_eur?:number|null;company_size?:string;role?:string}){if(!client)throw new Error('database_unavailable');await client.execute({sql:'INSERT INTO idea_votes(idea_key,vote,willing_to_pay,price_eur,company_size,role) VALUES(?,?,?,?,?,?)',args:['conforva',input.vote,input.willing_to_pay?1:0,input.price_eur??null,input.company_size||null,input.role||null]});return getIdeaVoteStats()}
export async function getIdeaVoteStats(){if(!client)return {total:0,yes:0,no:0,yes_percent:0,willing_to_pay:0,average_price_eur:null};const r=await client.execute({sql:`SELECT COUNT(*) total,SUM(CASE WHEN vote='yes' THEN 1 ELSE 0 END) yes,SUM(CASE WHEN vote='no' THEN 1 ELSE 0 END) no,SUM(willing_to_pay) willing_to_pay,AVG(CASE WHEN willing_to_pay=1 THEN price_eur END) average_price_eur FROM idea_votes WHERE idea_key=?`,args:['conforva']});const x=r.rows[0]||{};const total=Number(x.total||0),yes=Number(x.yes||0);return {total,yes,no:Number(x.no||0),yes_percent:total?Math.round(yes*100/total):0,willing_to_pay:Number(x.willing_to_pay||0),average_price_eur:x.average_price_eur==null?null:Number(x.average_price_eur)}}
const hashKey=(key:string)=>createHash('sha256').update(key).digest('hex');
export async function createApiKey(o:string,name:string,environment='production'){if(!client)throw new Error('database_unavailable');const id='key_'+randomBytes(10).toString('hex'),secret='cnf_'+randomBytes(32).toString('hex'),now=new Date().toISOString();await client.execute({sql:'INSERT INTO api_keys(id,organization_id,name,key_prefix,secret_hash,environment,created_at) VALUES(?,?,?,?,?,?,?)',args:[id,o,name.trim()||'API key',secret.slice(0,12),hashKey(secret),environment,now]});return {id,name:name.trim()||'API key',key:secret,prefix:secret.slice(0,12),environment,created_at:now}}
export async function listApiKeys(o:string){if(!client)return[];const r=await client.execute({sql:'SELECT id,name,key_prefix,environment,created_at,revoked_at FROM api_keys WHERE organization_id=? ORDER BY created_at DESC',args:[o]});return r.rows.map(x=>({id:String(x.id),name:String(x.name),prefix:String(x.key_prefix),environment:String(x.environment),created_at:String(x.created_at),status:x.revoked_at?'revoked':'active'}))}
export async function revokeApiKey(o:string,id:string){if(!client)throw new Error('database_unavailable');const r=await client.execute({sql:'UPDATE api_keys SET revoked_at=? WHERE id=? AND organization_id=? AND revoked_at IS NULL',args:[new Date().toISOString(),id,o]});return r.rowsAffected>0}
export async function authenticateApiKey(key:string){if(!client||!key)return null;const r=await client.execute({sql:'SELECT id,organization_id FROM api_keys WHERE secret_hash=? AND revoked_at IS NULL',args:[hashKey(key)]});const x=r.rows[0];return x?{id:String(x.id),organization_id:String(x.organization_id)}:null}
export async function recordUsage(o:string,apiKeyId:string|undefined,model:string,type:string,input=0,output=0,cost=0){if(!client)return;await client.execute({sql:'INSERT INTO usage_events(organization_id,api_key_id,model,request_type,input_tokens,output_tokens,cost_eur,created_at) VALUES(?,?,?,?,?,?,?,?)',args:[o,apiKeyId||null,model,type,input,output,cost,new Date().toISOString()]})}
export async function getUsage(o:string){if(!client)return {requests:0,input_tokens:0,output_tokens:0,cost_eur:0};const r=await client.execute({sql:'SELECT COUNT(*) requests,COALESCE(SUM(input_tokens),0) input_tokens,COALESCE(SUM(output_tokens),0) output_tokens,COALESCE(SUM(cost_eur),0) cost_eur FROM usage_events WHERE organization_id=?',args:[o]});const x=r.rows[0]||{};return {requests:Number(x.requests||0),input_tokens:Number(x.input_tokens||0),output_tokens:Number(x.output_tokens||0),cost_eur:Number(x.cost_eur||0)}}
export async function getBilling(o:string){if(!client)return null;const r=await client.execute({sql:'SELECT stripe_customer_id, stripe_subscription_id, plan, status, period_end, cancel_at_period_end, updated_at FROM billing_accounts WHERE organization_id=?',args:[o]});const x=r.rows[0];return x?{stripe_customer_id:String(x.stripe_customer_id||''),stripe_subscription_id:String(x.stripe_subscription_id||''),plan:x.plan?String(x.plan):null,status:x.status?String(x.status):null,period_end:x.period_end?String(x.period_end):null,cancel_at_period_end:Boolean(Number(x.cancel_at_period_end||0)),updated_at:String(x.updated_at)}:null}
export async function saveBilling(o:string,data:{customer_id?:string|null;subscription_id?:string|null;plan?:string|null;status?:string|null;period_end?:string|null;cancel_at_period_end?:boolean}){if(!client)throw new Error('database_unavailable');const old=await getBilling(o),now=new Date().toISOString();await client.execute({sql:`INSERT INTO billing_accounts(organization_id,stripe_customer_id,stripe_subscription_id,plan,status,period_end,cancel_at_period_end,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(organization_id) DO UPDATE SET stripe_customer_id=excluded.stripe_customer_id,stripe_subscription_id=excluded.stripe_subscription_id,plan=excluded.plan,status=excluded.status,period_end=excluded.period_end,cancel_at_period_end=excluded.cancel_at_period_end,updated_at=excluded.updated_at`,args:[o,data.customer_id??old?.stripe_customer_id||null,data.subscription_id??old?.stripe_subscription_id||null,data.plan??old?.plan||null,data.status??old?.status||null,data.period_end??old?.period_end||null,data.cancel_at_period_end??old?.cancel_at_period_end?1:0,now]});return getBilling(o)}
export async function findOrganizationByCustomer(customerId:string){if(!client)return null;const r=await client.execute({sql:'SELECT organization_id FROM billing_accounts WHERE stripe_customer_id=?',args:[customerId]});return r.rows[0]?String(r.rows[0].organization_id):null}
export async function findOrganizationBySubscription(subscriptionId:string){if(!client)return null;const r=await client.execute({sql:'SELECT organization_id FROM billing_accounts WHERE stripe_subscription_id=?',args:[subscriptionId]});return r.rows[0]?String(r.rows[0].organization_id):null}