import { createHmac, timingSafeEqual } from 'node:crypto';

const secret=()=>process.env.STRIPE_SECRET_KEY||'';
const priceIds:Record<string,string|undefined>={starter:process.env.STRIPE_PRICE_STARTER,growth:process.env.STRIPE_PRICE_GROWTH,pro:process.env.STRIPE_PRICE_PRO};
const api=async(path:string,params:Record<string,string|undefined>={})=>{if(!secret())throw new Error('stripe_not_configured');const body=new URLSearchParams();for(const [k,v] of Object.entries(params))if(v!==undefined)body.set(k,v);const r=await fetch(`https://api.stripe.com/v1/${path}`,{method:'POST',headers:{Authorization:`Bearer ${secret()}`,'Content-Type':'application/x-www-form-urlencoded'},body});const data:any=await r.json();if(!r.ok)throw new Error(data?.error?.message||'stripe_request_failed');return data};
export const stripeEnabled=Boolean(secret());
export const PLANS={
  starter:{name:'Starter',price_eur:29,included_usage_eur:10,max_agents:3,monthly_requests:0,features:['3 agents','10 € API usage included / month','Policies and deterministic controls','AI security verification','Audit history and sandbox']},
  growth:{name:'Growth',price_eur:79,included_usage_eur:35,max_agents:15,monthly_requests:0,features:['15 agents','35 € API usage included / month','Everything in Starter','Full API access and usage tracking','Incidents, audit evidence and integrations']},
  pro:{name:'Pro',price_eur:199,included_usage_eur:100,max_agents:50,monthly_requests:0,features:['50 agents','100 € API usage included / month','Everything in Growth','Advanced autonomous-agent governance','Priority limits and production controls']}
} as const;
export function priceForPlan(plan:string){return priceIds[plan]||null}
export function planDetails(plan:string){return PLANS[plan as keyof typeof PLANS]||null}
export async function createCustomer(email:string,name:string,organizationId:string){return api('customers',{email,name,description:`Conforva organization ${organizationId}`,'metadata[organization_id]':organizationId})}
export async function createCheckoutSession(input:{customerId?:string;email:string;name:string;organizationId:string;plan:string;successUrl:string;cancelUrl:string;trialDays?:number}){const price=priceForPlan(input.plan);if(!price)throw new Error('stripe_price_not_configured');const customer=input.customerId|| (await createCustomer(input.email,input.name,input.organizationId)).id;const params:Record<string,string|undefined>={'mode':'subscription',customer,'line_items[0][price]':price,'line_items[0][quantity]':'1','success_url':input.successUrl,'cancel_url':input.cancelUrl,'allow_promotion_codes':'true','billing_address_collection':'auto','metadata[organization_id]':input.organizationId,'metadata[plan]':input.plan,'subscription_data[metadata][organization_id]':input.organizationId,'subscription_data[metadata][plan]':input.plan};if(input.trialDays&&input.trialDays>0)params['subscription_data[trial_period_days]']=String(input.trialDays);return api('checkout/sessions',params)}
export async function createPortalSession(customerId:string,returnUrl:string){return api('billing_portal/sessions',{customer:customerId,return_url:returnUrl})}
export function verifyWebhook(payload:Buffer|string,signature:string){const whsec=process.env.STRIPE_WEBHOOK_SECRET;if(!whsec)throw new Error('stripe_webhook_not_configured');const parts=Object.fromEntries(signature.split(',').map(x=>x.split('='))) as Record<string,string>;const timestamp=parts.t;const provided=parts.v1;if(!timestamp||!provided)throw new Error('invalid_stripe_signature');if(Math.abs(Date.now()/1000-Number(timestamp))>300)throw new Error('stripe_signature_expired');const signed=`${timestamp}.${Buffer.isBuffer(payload)?payload.toString('utf8'):payload}`;const expected=createHmac('sha256',whsec).update(signed).digest('hex');const a=Buffer.from(expected),b=Buffer.from(provided);if(a.length!==b.length||!timingSafeEqual(a,b))throw new Error('invalid_stripe_signature');return JSON.parse(Buffer.isBuffer(payload)?payload.toString('utf8'):payload)}