import { createHmac, timingSafeEqual } from 'node:crypto';

const secret=()=>process.env.STRIPE_SECRET_KEY||'';
const priceIds:Record<string,string|undefined>={starter:process.env.STRIPE_PRICE_STARTER,growth:process.env.STRIPE_PRICE_GROWTH,pro:process.env.STRIPE_PRICE_PRO};
const api=async(path:string,params:Record<string,string|undefined>={})=>{if(!secret())throw new Error('stripe_not_configured');const body=new URLSearchParams();for(const [k,v] of Object.entries(params))if(v!==undefined)body.set(k,v);const r=await fetch(`https://api.stripe.com/v1/${path}`,{method:'POST',headers:{Authorization:`Bearer ${secret()}`,'Content-Type':'application/x-www-form-urlencoded'},body});const data:any=await r.json();if(!r.ok)throw new Error(data?.error?.message||'stripe_request_failed');return data};
export const stripeEnabled=Boolean(secret());
export const PLANS={starter:{name:'Starter',price_eur:29,included_credit_eur:10,max_agents:3,monthly_requests:10000},growth:{name:'Growth',price_eur:79,included_credit_eur:35,max_agents:15,monthly_requests:50000},pro:{name:'Pro',price_eur:199,included_credit_eur:100,max_agents:50,monthly_requests:200000}} as const;
export const CREDIT_PACKS={10:{price_eur:10,credit_eur:10},25:{price_eur:23,credit_eur:25},50:{price_eur:42,credit_eur:50},100:{price_eur:75,credit_eur:100}} as const;
export function priceForPlan(plan:string){return priceIds[plan]||null}
export function planDetails(plan:string){return PLANS[plan as keyof typeof PLANS]||null}
export async function createCustomer(email:string,name:string,organizationId:string){return api('customers',{email,name,description:`Conforva organization ${organizationId}`,'metadata[organization_id]':organizationId})}
export async function createCheckoutSession(input:{customerId?:string;email:string;name:string;organizationId:string;plan:string;successUrl:string;cancelUrl:string}){const price=priceForPlan(input.plan);if(!price)throw new Error('stripe_price_not_configured');const customer=input.customerId|| (await createCustomer(input.email,input.name,input.organizationId)).id;return api('checkout/sessions',{'mode':'subscription',customer,'line_items[0][price]':price,'line_items[0][quantity]':'1','success_url':input.successUrl,'cancel_url':input.cancelUrl,'allow_promotion_codes':'true','billing_address_collection':'auto','metadata[organization_id]':input.organizationId,'metadata[plan]':input.plan,'subscription_data[metadata][organization_id]':input.organizationId,'subscription_data[metadata][plan]':input.plan})}
export async function createCreditCheckoutSession(input:{customerId:string;organizationId:string;pack:keyof typeof CREDIT_PACKS;successUrl:string;cancelUrl:string}){const priceId=process.env[`STRIPE_PRICE_CREDITS_${input.pack}`];if(!priceId)throw new Error('stripe_credit_price_not_configured');const pack=CREDIT_PACKS[input.pack];return api('checkout/sessions',{'mode':'payment',customer:input.customerId,'line_items[0][price]':priceId,'line_items[0][quantity]':'1','success_url':input.successUrl,'cancel_url':input.cancelUrl,'metadata[organization_id]':input.organizationId,'metadata[purchase_type]':'api_credits','metadata[credit_eur]':String(pack.credit_eur),'metadata[pack_eur]':String(input.pack)})}
export async function createPortalSession(customerId:string,returnUrl:string){return api('billing_portal/sessions',{customer:customerId,return_url:returnUrl})}
export function verifyWebhook(payload:Buffer|string,signature:string){const whsec=process.env.STRIPE_WEBHOOK_SECRET;if(!whsec)throw new Error('stripe_webhook_not_configured');const parts=Object.fromEntries(signature.split(',').map(x=>x.split('='))) as Record<string,string>;const timestamp=parts.t;const provided=parts.v1;if(!timestamp||!provided)throw new Error('invalid_stripe_signature');if(Math.abs(Date.now()/1000-Number(timestamp))>300)throw new Error('stripe_signature_expired');const signed=`${timestamp}.${Buffer.isBuffer(payload)?payload.toString('utf8'):payload}`;const expected=createHmac('sha256',whsec).update(signed).digest('hex');if(!timingSafeEqual(Buffer.from(expected),Buffer.from(provided)))throw new Error('invalid_stripe_signature');return JSON.parse(Buffer.isBuffer(payload)?payload.toString('utf8'):payload)}